### ISSUE TITLE
Add initial support for Docker volumes

### ISSUE THREAD

**Issue by psviderski** [psviderski/uncloud#47]
When a volume is specified in a compose file without `external: true`:
* A new volume is created on a suitable machine if the volume with the provided name doesn't exist on any machine yet
* All services in the Compose and their replicas are scheduled on this machine sharing the same volume

When a volume is specified with `external:true`:
* A volume must be manually created in the cluster on any machine before deploying a Compose. Deployment will fail if the volume doesn't exist
* All services in the Compose and their replicas are scheduled on the machine with a volume sharing it

Additionally, a volume with the same name can be manually created on multiple machines. In this case, services can be scheduled on any machine that contains the volume.

## TODO
* [x] Define proto for volume management rpc methods (Create, List, Remove)
* [x] Implement the Docker server and client for volume methods
* [x] Define volume and mount specs on `ServiceSpec` and `ContainerSpec` (support named Docker volumes, host bind, tmpfs)
* [x] Implement validation for new volume specs
* [x] Map volume and mount specs to container config when creating a container
* [x] Fail service container creation if the named volume doesn't exist (no auto-creation for now)
* [x] Update diff function `EvalContainerSpecChange`
* [x] Update e2e tests using new volumes
* [x] Parse `-v|--volume` into `VolumeSpec` and create a volume before deploying
* [x] Apply a placement filter for service containers when deploying a service with volumes
* [x] Implement `VolumeScheduler` to determine which machines new volumes need to be created on for a set of services to satisfy their scheduling constraints
* [x] Refactor `service run` command to use `VolumeScheduler` in `RunService`
* [x] Map Compose volumes to new volume specs in service specs
* [x] Update Compose deployments to precreate non-external volumes
* [x] Provide human-friendly error messages when scheduling fails because of a placement or volume constraint
* [x] Management CLI commands: #48

**Comment by psviderski** [comment]
Volume support has been implemented for Compose deployments.

Example compose from `test/e2e/fixtures/compose-volumes.yaml`:
```
name: my-name
services:
  test-compose-volumes-service1:
    image: portainer/pause:3.9
    volumes:
      - test-compose-volumes-data1:/data1
      - /etc/passwd:/host/etc/passwd:ro
    deploy:
      replicas: 3
  test-compose-volumes-service2:
    image: portainer/pause:3.9
    volumes:
      - type: volume
        source: test-compose-volumes-data2-alias
        target: /data2/long/syntax
    deploy:
      replicas: 2
  test-compose-volumes-service3:
    image: portainer/pause:3.9
    volumes:
      - test-compose-volumes-data2-alias:/data2
      - test-compose-volumes-external:/external:ro

volumes:
  test-compose-volumes-data1:
  test-compose-volumes-data2-alias:
    name: test-compose-volumes-data2
    driver: local
  test-compose-volumes-external:
    # Must be created manually before deploying this compose file.
    external: true
```

<img width="783" alt="Image" src="https://github.com/user-attachments/assets/7d0a7ef8-4bbc-4e98-af27-123476ab69ee" />
