### ISSUE TITLE
Add support for Compose secrets with custom drivers

### ISSUE THREAD

**Issue by psviderski** [psviderski/uncloud#76]
Basic secrets support from files: https://github.com/psviderski/uncloud/issues/75

I'm thinking of extending the Compose secrets spec using custom drivers in a similar way compose uses drivers for volumes or logging. Still keep them client side but allow to fetch them from popular secrets managers. See how Kamal supports various secret adapters: https://kamal-deploy.org/docs/commands/secrets/

Something like this:
```
secrets:
  my_secret:
    driver: 1password|bitwarden|vault
    driver_opts:
      path: Vault/secret_name/field_name
```

**Comment by fredix** [comment]
Hi !
maybe I can suggest to replace vault with openbao (https://openbao.org/). With the acquisition of Hashicorp, the Vault API could diverge, and only Openbao is under a free license. Unless you think you can handle both ?

**Comment by hrstoyanov** [comment]
I was gonna ask for this in discord, but very happy it is on your radar already! Kamal's integrations are genius - I love how they leverage the various CLIs. Not sure how much of these can be incorporated in UC, but an AI agent can look at the Kamal code and translate them to Go and UC quickly - these wrappers are not very difficult code, imo.

**Comment by psviderski** [comment]
Just stumbled upon a project that implements 1password secret driver for Docker Swarm: https://github.com/MrMarble/opsd

**Comment by hrstoyanov** [comment]
@psviderski there are a lot of secrets stores out there, I would suggest use the cli as kamal does, it would be hard to get apis for all.

**Comment by psviderski** [comment]
I agree, supporting an arbitrary command would cover most of the use cases so this should definitely be supported first 👍

**Comment by hrstoyanov** [comment]
A suggested hack - get your favorite AI thing and ask it to translate all the Kamal secrets  Ruby code into Go! I think the  Kamal team covered almost everything out there by now  .. you will have 80% done in no time. The rest should be mostly testing ...

**Comment by miekg** [comment]
seems both configs and secrets could benefit from an `x-command` option that runs the command, captures stdout and uses *that* as the config/secret.

For secrets this would mean a single API to support, while keeping the entirety of how to do secrets out of uncloud.

## update

it does make your compose file non-portable... I can see that being "not good"

**Comment by miekg** [comment]
#401 implements something similar to 'secrets engine', if we want to support defining how to get the secret *in the compose file*, like so:
```yaml
services:
  alpine:
    image: alpine
    environment:
      BLA: secret://geheim

secrets:
  geheim:
    driver_opts:
      command: blaat
```
the docker compose loader complains: `Error: load compose file(s): secrets.geheim: one of file|environment must be set`

I guess a solution is to use an extensions `x-secrets`, with 
```yaml
x-secrets
   geheim:
     driver_opts:
     command: blaat
```
by why bother with `driver` and `driver_opts` at all then?

In #401 this is all hidden from you, because the "how to get the secret" is encoded in the Go code. I can see value in having it in your compose file, but is that really that important? I.e. if you use `fnox` wouldn't all your secret definition then be
`command: fnox get <secret>` multiple times?
