### ISSUE TITLE
Hosting PostgreSQL

### ISSUE THREAD

**Issue by tadas-subonis** [psviderski/uncloud#78]
Hey,

what's the best way to host PostgreSQL using uncloud? How would config look like?

**Comment by iRazvan2745** [comment]
Pretty sure you can host postgres, but cant scale it.

**Comment by tonyo** [comment]
An example Compose-like config for running postgres with a data volume could look like: 

```yaml
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: YOURAPP_IMAGE
    environment:
      DATABASE_URL: postgres://admin:${ADMIN_PASSWORD}@postgres:5432/mydb
    x-ports:
      - basic.example.com:80/https

volumes:
  postgres_data:
```

After updating it with your image and setting ADMIN_PASSWORD environment variable, it would be deployed with `uc deploy` command.

A few notes:
* [`depends_on` Compose feature](https://docs.docker.com/compose/how-tos/startup-order/) is normally used to establish the service dependencies and that the app should start after the database, but it's not yet fully implemented in Uncloud, so your app might need to retry until the postgres container is ready.
* Usual recommendations on running postgres and databases in containers (and in production) apply
